# Generated by Django 5.0.3 on 2024-03-23 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0010_tbl_employee'),
        ('Seller', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_productimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_details', models.CharField(max_length=50)),
                ('productimage_photo', models.FileField(upload_to='Assets/GallaryPhoto/')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_subcategory')),
            ],
        ),
    ]
