# Generated by Django 5.0.3 on 2024-03-23 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_tbl_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_productimages',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='tbl_productimages',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_product'),
        ),
    ]
