# Generated by Django 5.0.3 on 2024-03-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0005_remove_tbl_productimages_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_productimages',
            name='product_name',
        ),
    ]
