# Generated by Django 5.0.3 on 2024-03-28 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_seller'),
        ('Seller', '0006_remove_tbl_productimages_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='sellerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_seller'),
        ),
    ]
