# Generated by Django 5.0.2 on 2024-03-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0002_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_category', models.CharField(max_length=50)),
            ],
        ),
    ]
