# Generated by Django 5.0.2 on 2024-03-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0003_tbl_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_category',
            old_name='admin_category',
            new_name='category_name',
        ),
    ]
