# Generated by Django 5.0.2 on 2024-03-08 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0009_tbl_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_contact', models.CharField(max_length=50)),
                ('employee_salary', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_designation')),
            ],
        ),
    ]
