# Generated by Django 5.0.2 on 2024-03-09 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0010_tbl_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newuser_name', models.CharField(max_length=50)),
                ('newuser_address', models.CharField(max_length=50)),
                ('newuser_contact', models.CharField(max_length=50)),
                ('newuser_email', models.CharField(max_length=50)),
                ('newuser_password', models.CharField(max_length=50)),
                ('distict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_district')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
