# Generated by Django 5.0.2 on 2024-03-09 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0010_tbl_employee'),
        ('Guest', '0003_tbl_user_delete_tbl_newuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('seller_address', models.CharField(max_length=50)),
                ('seller_contact', models.CharField(max_length=50)),
                ('seller_email', models.CharField(max_length=50)),
                ('seller_password', models.CharField(max_length=50)),
                ('seller_photo', models.FileField(upload_to='Assets/SellerPhoto/')),
                ('seller_proof', models.FileField(upload_to='Assets/SellerProof/')),
                ('seller_status', models.IntegerField(default='0')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
