# Generated by Django 5.0.3 on 2024-03-27 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0004_tbl_seller'),
        ('Seller', '0006_remove_tbl_productimages_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_data', models.CharField(max_length=50)),
                ('booking_amount', models.CharField(max_length=50)),
                ('booking_status', models.IntegerField(default='0')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_status', models.IntegerField(default='0')),
                ('cart_quantity', models.IntegerField(max_length=50)),
                ('bookingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_product')),
            ],
        ),
    ]
