# Generated by Django 5.0.3 on 2024-04-25 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_seller'),
        ('User', '0002_tbl_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_history',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
    ]
